name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: cache deno installation and deno.land dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno/deps/https/deno.land

      - name: install or update deno installation
        run: |
          export DENO_INSTALL="/home/runner/.deno"
          export PATH="${DENO_INSTALL}/bin:${PATH}"
          mkdir -p "${DENO_INSTALL}"
          deno upgrade --canary || (
            curl -fsSL https://deno.land/x/install/install.sh > "${DENO_INSTALL}/.sh";
            sh "${DENO_INSTALL}/.sh"
          )
          deno upgrade --canary
          deno --version
          deno info
          echo "DENO_INSTALL=${DENO_INSTALL}" >> "${GITHUB_ENV}"
          echo "PATH=${PATH}" >> "${GITHUB_ENV}"

      - name: tag release using ./VERSION and merge it into trunk
        run: |
          declare br="
          "
          declare version="$(eval "echo $(cat ./VERSION)")"
          deno eval '
            import * as semver from "https://deno.land/x/semver@v1.0.0/mod.ts";
            const [version] = Deno.args;
            if (semver.valid(version)) {
              console.log(`version is valid: ${version}`);
            } else {
              console.log(`version is NOT valid: ${version}`);
              Deno.exit(1);
            }
          ' "${version}"
          git tag "${version}"
          git push origin HEAD:trunk
          git push origin "${version}"
