name: Tag Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Tag Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: create and push tag from ./version
        run: |
          declare br="
          "
          declare version="$(eval "echo $(cat ./VERSION)")"
          deno eval '
            import * as semver from "https://deno.land/x/semver@v1.0.0/mod.ts";
            const [version] = Deno.args;
            if (semver.valid(version)) {
              console.log(`version is valid: ${version}`);
            } else {
              console.log(`version is NOT valid: ${version}`);
              Deno.exit(1);
            }
          ' "${version}"
          declare author_name="$(git log -1 --pretty=format:'%an')"
          declare author_email="$(git log -1 --pretty=format:'%ae')"
          declare current_action_url="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${{ github.run_id }}"
          export GIT_TAGGER_NAME="${{ github.actor }}"
          export GIT_TAGGER_EMAIL="41898282+github-actions[bot]@users.noreply.github.com"
          git tag "${version}" -a -m "v${version}${br}${br}${current_action_url}"
          git push origin "${version}"
